## Project Information
site_name: XYY's Notebook                           ## 显示在左上角和标签页上的站点名字
site_url: https://note.starlightxyy.cn              ## 点击站点名字跳转到的网址
repo_url: https://github.com/amorphophallus/note    ## 右上角 icon 的跳转地址
repo_name: note-github                              ## 右上角 icon 的备注文字
edit_uri: edit/main/docs                            ## 文章目录左侧的编辑按钮的跳转地址
site_description: Note about everything.
theme:
    name: material
    features:
        - navigation.tabs                           ## 启用顶端导航
        - navigation.sections                       ## 展开侧边导航
        - navigation.indexes                        ## 启用章节概览 index.md
        - navigation.top                            ## 启用回到顶部按钮
        - content.tabs.link                         ## 
    palette:

        # Palette toggle for automatic mode
        - media: "(prefers-color-scheme)"
          toggle:
            icon: material/brightness-auto
            name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default 
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
            icon: material/brightness-4
            name: Switch to system preference




## Documentation Layout
nav:
    - 'About': 
        - 'index.md'
        - 'TAG': 'tags.md'
    - 'Server':
        - 'Fundamental':
            - 'Linux Command': 'Server/Fundamental/Linux Command.md'
            - 'vim': 'Server/Fundamental/vim.md'
            - 'git':
                - '常见操作': 'Server/Fundamental/Git-learning/常见操作.md'
                - '常见问题': 'Server/Fundamental/Git-learning/常见问题.md'
            - 'WSL': 'Server/Fundamental/WSL.md'
            - 'Docker': 'Server/Fundamental/Docker.md'
            - 'Caddy': 'Server/Fundamental/Caddy.md'
            - 'SSH': 'Server/Fundamental/SSH.md'
        - 'StarLightXYY':
            - 'Server/starLightXYY/index.md'                                                    ## 章节概览使用方式:index.md
            - 'Docker + Typecho 搭建博客': 'Server/starLightXYY/Docker + Typecho 搭建博客.md'
            - '服务器部署 overleaf': 'Server/starLightXYY/服务器部署 overleaf.md'
            - 'mkdocs 部署笔记文档': 'Server/starLightXYY/mkdocs 部署笔记文档.md'
            - '服务器数据迁移': 'Server/starLightXYY/服务器数据迁移.md'
            - 'Reference':
                - 'tags': 'Server/starLightXYY/Reference/mkdocs-tags.md'
                - 'roamlinks': 'Server/starLightXYY/Reference/mkdocs-roamlinks-plugin.md'
                - 'content tabs': 'Server/starLightXYY/Reference/mkdocs-contenttabs.md'
    - 'Front End':
        - 'html': 'Front End/html.md'
        - 'javascript': 'Front End/javascript.md'
        - 'css': 'Front End/css.md'
        - 'react': 'Front End/react.md'
        - 'antd': 'Front End/antd.md'
    - 'Programming Tools':
        - 'LaTeX':
            - 'Programming Tools/LATEX/index.md'
        - 'Python':
            - 'Python': 'Programming Tools/Python/python.md'
            - 'Numpy': 'Programming Tools/Python/Numpy.md'
            - 'PyCharm + Anaconda 配置环境': 'Programming Tools/Python/PyCharm + Anaconda.md'
            - 'Pytorch 实现 Lenet-5 网络模型': 'Programming Tools/Python/Pytorch 实现 Lenet 网络模型.md'
            - 'Pytorch 实现 GPT-2 网络模型': 'Programming Tools/Python/Pytorch 实现 GPT-2 网络模型.md'
        - 'C#':
            - 'C# Basic': 'Programming Tools/C#/basic.md'
            - 'C#, JS 相互转化': 'Programming Tools/C#/C#, JS 相互转化.md'
        - 'C++':
            - 'C++技巧': 'Programming Tools/C++/C++技巧.md'
            - 'C++多文件结构': 'Programming Tools/C++/C++ multiple program structure.md'
            - 'Makefile': 'Programming Tools/C++/makefile.md'
        - 'VScode':
            - 'plugins': 'Programming Tools/VScode/plugins.md'
            - 'foam': 'Programming Tools/VScode/VScode-foam.md'
            - 'VScode 调试 C/C++ 代码': 'Programming Tools/VScode/VScode 调试 C 和 C++ 代码.md'
        - 'Visual Studio':
            - 'Programming Tools/VS/index.md'
        - '微信小程序':
            - '基础知识': 'Programming Tools/WX miniprogram/基础知识.md'
        - 'markdown转pdf': 'Programming Tools/markdown转pdf.md'
        - 'Others': 'Programming Tools/others.md'
    - 'Projects':
        - 'box-2021':
            - '项目总结': 'Projects/box-2021 项目总结.md'
        - 'rop-neo-front':
            - '内训笔记': 'Projects/rop-neo-front/内训笔记.md'
            - '项目笔记': 'Projects/rop-neo-front/项目笔记.md'
        - 'android':
            - '笔记': 'Projects/android/笔记.md'
    - 'College Courses':
        - 'Tools':
            - 'word学习笔记': 'College Courses/Tools/word学习笔记.md'
            - '论文相关': 'College Courses/Tools/论文相关.md'
        - '网安导':
            - '笔记': 'College Courses/网安导/笔记.md'
            - '实验报告': 'College Courses/网安导/实验报告.md'
        - '超算 HPC':
            - 'CUDA 基础': 'College Courses/HPC/CUDA 基础.md'
            - 'CUDA 优化': 'College Courses/HPC/CUDA 优化.md'
            - '手写 SIMD 向量化': 'College Courses/HPC/手写 SIMD 向量化.md'
        - 'Introduction to Computing System':
            - '复习提纲': 'College Courses/Introduction to Computing System/复习提纲.md'
        - '课程计划':
            - '大二秋冬学期学习计划': 'College Courses/课程计划/大二秋冬学期学习计划.md'
        - '大二秋冬笔记':
            - 'AI基础': 'College Courses/大二秋冬笔记/AI基础.md'
            - '博弈论基础': 'College Courses/大二秋冬笔记/博弈论基础.md'
            - 'FDS': 'College Courses/大二秋冬笔记/FDS.md'
            - '计逻': 'College Courses/大二秋冬笔记/计逻.md'
            - 'DIP': 'College Courses/大二秋冬笔记/DIP.md'
            - '数字全息技术': 'College Courses/大二秋冬笔记/数字全息技术.md'
            - '程算': 'College Courses/大二秋冬笔记/程算.md'
            - '概率论': 'College Courses/大二秋冬笔记/概率论.md'
    - 'Others':
        - '经验':
            - '本科毕业出路经验分享': 'Others/经验/本科毕业出路经验分享.md'
            - '寒假社会实践经验总结': 'Others/经验/寒假社会实践经验总结.md'
            - '职规学长学姐经验分享': 'Others/经验/职规学长学姐经验分享.md'
            - '图灵学长经验分享-兴趣': 'Others/经验/图灵学长经验分享-兴趣.md'
        - '兴趣':
            - 'AE学习': 'Others/兴趣/AE学习.md'
            - 'pr小技巧': 'Others/兴趣/pr小技巧.md'
            - '篮球运球': 'Others/兴趣/篮球运球.md'
            - '素描课程笔记（知识点篇）': 'Others/兴趣/素描课程笔记（知识点篇）.md'
            - '素描课程笔记（练习篇）': 'Others/兴趣/素描课程笔记（练习篇）.md'
        - '日常':
            - '发型': 'Others/日常/发型.md'
        - 'Something to read':
            - 'Others/something to read/index.md'
        - '杭州':
            - 'Others/杭州/index.md'
            - 'Plan A': 'Others/杭州/PlanA.md'
            # - 'Plan B': 'Others/杭州/PlanB.md'
        - '旅游':
            - '贵州游记': 'Others/旅游/贵州游记.md'

# Extensions
markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences            # content tabs
  - pymdownx.tabbed:
      alternate_style: true 

# plugins
plugins:
    - search
    - roamlinks
    - tags:
        tags_file: tags.md