site_name: XYY's Notebook
site_url: https://note.starlightxyy.cn
repo_url: https://github.com/amorphophallus/note
repo_name: GitHub
site_description: Note about everything.
theme:
    name: material

